[package]
name = "qpas"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
serde = "1.0.217"
serde_json = "1.0.138"
serde_qs = "0.13.0"
url = "2.5.4"
